/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppLedgerRouteImport } from './routes/_app/ledger'
import { Route as AppReceiveRouteImport } from './routes/_app/receive'
import { Route as AppStockRouteImport } from './routes/_app/stock'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppCountsIndexRouteImport } from './routes/_app/counts/index'
import { Route as AppCountsCountIdRouteImport } from './routes/_app/counts/$countId'
import { Route as AppCountsNewRouteImport } from './routes/_app/counts/new'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders/index'
import { Route as AppOrdersOrderIdRouteImport } from './routes/_app/orders/$orderId'
import { Route as AppOrdersNewRouteImport } from './routes/_app/orders/new'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiveRoute = AppReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppCountsIndexRoute = AppCountsIndexRouteImport.update({
  id: '/counts/',
  path: '/counts/',
  getParentRoute: () => AppRoute,
} as any)
const AppCountsCountIdRoute = AppCountsCountIdRouteImport.update({
  id: '/counts/$countId',
  path: '/counts/$countId',
  getParentRoute: () => AppRoute,
} as any)
const AppCountsNewRoute = AppCountsNewRouteImport.update({
  id: '/counts/new',
  path: '/counts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/audit': typeof AppAuditRoute
  '/ledger': typeof AppLedgerRoute
  '/receive': typeof AppReceiveRoute
  '/stock': typeof AppStockRoute
  '/team': typeof AppTeamRoute
  '/counts/$countId': typeof AppCountsCountIdRoute
  '/counts/new': typeof AppCountsNewRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/counts/': typeof AppCountsIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/audit': typeof AppAuditRoute
  '/ledger': typeof AppLedgerRoute
  '/receive': typeof AppReceiveRoute
  '/stock': typeof AppStockRoute
  '/team': typeof AppTeamRoute
  '/': typeof AppIndexRoute
  '/counts/$countId': typeof AppCountsCountIdRoute
  '/counts/new': typeof AppCountsNewRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/counts': typeof AppCountsIndexRoute
  '/orders': typeof AppOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/ledger': typeof AppLedgerRoute
  '/_app/receive': typeof AppReceiveRoute
  '/_app/stock': typeof AppStockRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/': typeof AppIndexRoute
  '/_app/counts/$countId': typeof AppCountsCountIdRoute
  '/_app/counts/new': typeof AppCountsNewRoute
  '/_app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/_app/orders/new': typeof AppOrdersNewRoute
  '/_app/counts/': typeof AppCountsIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/audit'
    | '/ledger'
    | '/receive'
    | '/stock'
    | '/team'
    | '/counts/$countId'
    | '/counts/new'
    | '/orders/$orderId'
    | '/orders/new'
    | '/counts/'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/account'
    | '/audit'
    | '/ledger'
    | '/receive'
    | '/stock'
    | '/team'
    | '/'
    | '/counts/$countId'
    | '/counts/new'
    | '/orders/$orderId'
    | '/orders/new'
    | '/counts'
    | '/orders'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/account'
    | '/_app/audit'
    | '/_app/ledger'
    | '/_app/receive'
    | '/_app/stock'
    | '/_app/team'
    | '/_app/'
    | '/_app/counts/$countId'
    | '/_app/counts/new'
    | '/_app/orders/$orderId'
    | '/_app/orders/new'
    | '/_app/counts/'
    | '/_app/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger': {
      id: '/_app/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receive': {
      id: '/_app/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof AppReceiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/counts/': {
      id: '/_app/counts/'
      path: '/counts'
      fullPath: '/counts/'
      preLoaderRoute: typeof AppCountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/counts/$countId': {
      id: '/_app/counts/$countId'
      path: '/counts/$countId'
      fullPath: '/counts/$countId'
      preLoaderRoute: typeof AppCountsCountIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/counts/new': {
      id: '/_app/counts/new'
      path: '/counts/new'
      fullPath: '/counts/new'
      preLoaderRoute: typeof AppCountsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$orderId': {
      id: '/_app/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/new': {
      id: '/_app/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAuditRoute: typeof AppAuditRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppReceiveRoute: typeof AppReceiveRoute
  AppStockRoute: typeof AppStockRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCountsCountIdRoute: typeof AppCountsCountIdRoute
  AppCountsNewRoute: typeof AppCountsNewRoute
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRoute
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppCountsIndexRoute: typeof AppCountsIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAuditRoute: AppAuditRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppReceiveRoute: AppReceiveRoute,
  AppStockRoute: AppStockRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
  AppCountsCountIdRoute: AppCountsCountIdRoute,
  AppCountsNewRoute: AppCountsNewRoute,
  AppOrdersOrderIdRoute: AppOrdersOrderIdRoute,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppCountsIndexRoute: AppCountsIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
