// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counts.sql

package sqlc

import (
	"context"
	"time"
)

const countCounts = `-- name: CountCounts :one
SELECT count(*) FROM stock_counts c
WHERE ($1::text IS NULL OR c.status = $1::text)
`

func (q *Queries) CountCounts(ctx context.Context, status *string) (int64, error) {
	row := q.db.QueryRow(ctx, countCounts, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCount = `-- name: CreateCount :one
INSERT INTO stock_counts (status, note, created_by)
VALUES ('submitted', $1, $2)
RETURNING id
`

type CreateCountParams struct {
	Note      *string `json:"note"`
	CreatedBy *int64  `json:"created_by"`
}

func (q *Queries) CreateCount(ctx context.Context, arg CreateCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCount, arg.Note, arg.CreatedBy)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const decideCount = `-- name: DecideCount :exec
UPDATE stock_counts
SET status = $1, decided_by = $2, decided_at = now()
WHERE id = $3
`

type DecideCountParams struct {
	Status    string `json:"status"`
	DecidedBy *int64 `json:"decided_by"`
	ID        int64  `json:"id"`
}

func (q *Queries) DecideCount(ctx context.Context, arg DecideCountParams) error {
	_, err := q.db.Exec(ctx, decideCount, arg.Status, arg.DecidedBy, arg.ID)
	return err
}

const getCount = `-- name: GetCount :one
SELECT c.id, c.status, c.note, c.created_at, c.decided_at,
       cu.name AS created_by_name, du.name AS decided_by_name
FROM stock_counts c
LEFT JOIN users cu ON cu.id = c.created_by
LEFT JOIN users du ON du.id = c.decided_by
WHERE c.id = $1
`

type GetCountRow struct {
	ID            int64      `json:"id"`
	Status        string     `json:"status"`
	Note          *string    `json:"note"`
	CreatedAt     time.Time  `json:"created_at"`
	DecidedAt     *time.Time `json:"decided_at"`
	CreatedByName *string    `json:"created_by_name"`
	DecidedByName *string    `json:"decided_by_name"`
}

func (q *Queries) GetCount(ctx context.Context, id int64) (GetCountRow, error) {
	row := q.db.QueryRow(ctx, getCount, id)
	var i GetCountRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.CreatedByName,
		&i.DecidedByName,
	)
	return i, err
}

const insertCountLine = `-- name: InsertCountLine :execrows
INSERT INTO stock_count_lines (count_id, product_id, expected, counted)
SELECT $1, b.product_id, b.on_hand, $2
FROM stock_balances b
WHERE b.product_id = $3
`

type InsertCountLineParams struct {
	CountID   int64 `json:"count_id"`
	Counted   int32 `json:"counted"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) InsertCountLine(ctx context.Context, arg InsertCountLineParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCountLine, arg.CountID, arg.Counted, arg.ProductID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCountLines = `-- name: ListCountLines :many
SELECT l.product_id, p.sku, p.name, l.expected, l.counted, b.on_hand AS on_hand_now
FROM stock_count_lines l
JOIN products p ON p.id = l.product_id
JOIN stock_balances b ON b.product_id = l.product_id
WHERE l.count_id = $1
ORDER BY p.sku
`

type ListCountLinesRow struct {
	ProductID int64  `json:"product_id"`
	Sku       string `json:"sku"`
	Name      string `json:"name"`
	Expected  int32  `json:"expected"`
	Counted   int32  `json:"counted"`
	OnHandNow int32  `json:"on_hand_now"`
}

func (q *Queries) ListCountLines(ctx context.Context, countID int64) ([]ListCountLinesRow, error) {
	rows, err := q.db.Query(ctx, listCountLines, countID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountLinesRow{}
	for rows.Next() {
		var i ListCountLinesRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.Expected,
			&i.Counted,
			&i.OnHandNow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCounts = `-- name: ListCounts :many
SELECT c.id, c.status, c.note, c.created_at, c.decided_at,
       cu.name AS created_by_name,
       (SELECT count(*) FROM stock_count_lines l WHERE l.count_id = c.id) AS line_count,
       (SELECT count(*) FROM stock_count_lines l WHERE l.count_id = c.id AND l.counted <> l.expected) AS diff_count
FROM stock_counts c
LEFT JOIN users cu ON cu.id = c.created_by
WHERE ($1::text IS NULL OR c.status = $1::text)
ORDER BY c.created_at DESC, c.id DESC
LIMIT $3 OFFSET $2
`

type ListCountsParams struct {
	Status     *string `json:"status"`
	PageOffset int32   `json:"page_offset"`
	PageLimit  int32   `json:"page_limit"`
}

type ListCountsRow struct {
	ID            int64      `json:"id"`
	Status        string     `json:"status"`
	Note          *string    `json:"note"`
	CreatedAt     time.Time  `json:"created_at"`
	DecidedAt     *time.Time `json:"decided_at"`
	CreatedByName *string    `json:"created_by_name"`
	LineCount     int64      `json:"line_count"`
	DiffCount     int64      `json:"diff_count"`
}

func (q *Queries) ListCounts(ctx context.Context, arg ListCountsParams) ([]ListCountsRow, error) {
	rows, err := q.db.Query(ctx, listCounts, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountsRow{}
	for rows.Next() {
		var i ListCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Note,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.CreatedByName,
			&i.LineCount,
			&i.DiffCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCount = `-- name: LockCount :one
SELECT id, status FROM stock_counts WHERE id = $1 FOR UPDATE
`

type LockCountRow struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) LockCount(ctx context.Context, id int64) (LockCountRow, error) {
	row := q.db.QueryRow(ctx, lockCount, id)
	var i LockCountRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}
