// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID                int64              `json:"id"`
	Sku               string             `json:"sku"`
	Name              string             `json:"name"`
	Price             pgtype.Numeric     `json:"price"`
	LowStockThreshold int32              `json:"low_stock_threshold"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type StockBalance struct {
	ProductID int64              `json:"product_id"`
	OnHand    int32              `json:"on_hand"`
	Reserved  int32              `json:"reserved"`
	Version   int32              `json:"version"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type StockMovement struct {
	ID             int64              `json:"id"`
	ProductID      int64              `json:"product_id"`
	Type           string             `json:"type"`
	QtyChange      int32              `json:"qty_change"`
	ReservedChange int32              `json:"reserved_change"`
	RefType        *string            `json:"ref_type"`
	RefID          *int64             `json:"ref_id"`
	Reason         *string            `json:"reason"`
	CreatedBy      *int64             `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
