// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"
	"time"
)

const countOrders = `-- name: CountOrders :one
SELECT count(*)
FROM orders o
WHERE ($1::text IS NULL OR o.status = $1::text)
  AND ($2::text IS NULL OR o.order_no ILIKE '%' || $2::text || '%'
       OR o.external_ref ILIKE '%' || $2::text || '%')
`

type CountOrdersParams struct {
	Status *string `json:"status"`
	Search *string `json:"search"`
}

func (q *Queries) CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    channel, external_ref, status, note, created_by,
    customer_name, customer_phone, shipping_address, line_user_id
) VALUES (
    $1, $2, 'reserved', $3, $4,
    $5, $6, $7, $8
)
RETURNING id, order_no
`

type CreateOrderParams struct {
	Channel         string  `json:"channel"`
	ExternalRef     *string `json:"external_ref"`
	Note            *string `json:"note"`
	CreatedBy       *int64  `json:"created_by"`
	CustomerName    *string `json:"customer_name"`
	CustomerPhone   *string `json:"customer_phone"`
	ShippingAddress *string `json:"shipping_address"`
	LineUserID      *string `json:"line_user_id"`
}

type CreateOrderRow struct {
	ID      int64  `json:"id"`
	OrderNo string `json:"order_no"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.Channel,
		arg.ExternalRef,
		arg.Note,
		arg.CreatedBy,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.ShippingAddress,
		arg.LineUserID,
	)
	var i CreateOrderRow
	err := row.Scan(&i.ID, &i.OrderNo)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT o.id, o.order_no, o.channel, o.external_ref, o.status, o.total, o.note,
       u.name AS created_by_name, o.created_at, o.updated_at,
       o.packed_at, o.shipped_at, o.canceled_at,
       o.customer_name, o.customer_phone, o.shipping_address, o.line_user_id
FROM orders o
LEFT JOIN users u ON u.id = o.created_by
WHERE o.id = $1
`

type GetOrderRow struct {
	ID              int64      `json:"id"`
	OrderNo         string     `json:"order_no"`
	Channel         string     `json:"channel"`
	ExternalRef     *string    `json:"external_ref"`
	Status          string     `json:"status"`
	Total           string     `json:"total"`
	Note            *string    `json:"note"`
	CreatedByName   *string    `json:"created_by_name"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	PackedAt        *time.Time `json:"packed_at"`
	ShippedAt       *time.Time `json:"shipped_at"`
	CanceledAt      *time.Time `json:"canceled_at"`
	CustomerName    *string    `json:"customer_name"`
	CustomerPhone   *string    `json:"customer_phone"`
	ShippingAddress *string    `json:"shipping_address"`
	LineUserID      *string    `json:"line_user_id"`
}

func (q *Queries) GetOrder(ctx context.Context, id int64) (GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i GetOrderRow
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.Channel,
		&i.ExternalRef,
		&i.Status,
		&i.Total,
		&i.Note,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PackedAt,
		&i.ShippedAt,
		&i.CanceledAt,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.ShippingAddress,
		&i.LineUserID,
	)
	return i, err
}

const insertOrderItem = `-- name: InsertOrderItem :exec
INSERT INTO order_items (order_id, product_id, qty, unit_price)
VALUES ($1, $2, $3, $4)
`

type InsertOrderItemParams struct {
	OrderID   int64  `json:"order_id"`
	ProductID int64  `json:"product_id"`
	Qty       int32  `json:"qty"`
	UnitPrice string `json:"unit_price"`
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Qty,
		arg.UnitPrice,
	)
	return err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT oi.product_id, p.sku, p.name, oi.qty, oi.unit_price
FROM order_items oi
JOIN products p ON p.id = oi.product_id
WHERE oi.order_id = $1
ORDER BY oi.id
`

type ListOrderItemsRow struct {
	ProductID int64  `json:"product_id"`
	Sku       string `json:"sku"`
	Name      string `json:"name"`
	Qty       int32  `json:"qty"`
	UnitPrice string `json:"unit_price"`
}

func (q *Queries) ListOrderItems(ctx context.Context, orderID int64) ([]ListOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsRow{}
	for rows.Next() {
		var i ListOrderItemsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.Qty,
			&i.UnitPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT o.id, o.order_no, o.channel, o.external_ref, o.status, o.total,
       u.name AS created_by_name, o.created_at,
       (SELECT coalesce(sum(qty), 0)::integer FROM order_items WHERE order_id = o.id) AS item_count
FROM orders o
LEFT JOIN users u ON u.id = o.created_by
WHERE ($1::text IS NULL OR o.status = $1::text)
  AND ($2::text IS NULL OR o.order_no ILIKE '%' || $2::text || '%'
       OR o.external_ref ILIKE '%' || $2::text || '%')
ORDER BY o.created_at DESC, o.id DESC
LIMIT $4 OFFSET $3
`

type ListOrdersParams struct {
	Status     *string `json:"status"`
	Search     *string `json:"search"`
	PageOffset int32   `json:"page_offset"`
	PageLimit  int32   `json:"page_limit"`
}

type ListOrdersRow struct {
	ID            int64     `json:"id"`
	OrderNo       string    `json:"order_no"`
	Channel       string    `json:"channel"`
	ExternalRef   *string   `json:"external_ref"`
	Status        string    `json:"status"`
	Total         string    `json:"total"`
	CreatedByName *string   `json:"created_by_name"`
	CreatedAt     time.Time `json:"created_at"`
	ItemCount     int32     `json:"item_count"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.Status,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersRow{}
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.Channel,
			&i.ExternalRef,
			&i.Status,
			&i.Total,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrder = `-- name: LockOrder :one
SELECT id, order_no, status
FROM orders
WHERE id = $1
FOR UPDATE
`

type LockOrderRow struct {
	ID      int64  `json:"id"`
	OrderNo string `json:"order_no"`
	Status  string `json:"status"`
}

func (q *Queries) LockOrder(ctx context.Context, id int64) (LockOrderRow, error) {
	row := q.db.QueryRow(ctx, lockOrder, id)
	var i LockOrderRow
	err := row.Scan(&i.ID, &i.OrderNo, &i.Status)
	return i, err
}

const refreshOrderTotal = `-- name: RefreshOrderTotal :exec
UPDATE orders o
SET total = (SELECT coalesce(sum(oi.qty * oi.unit_price), 0) FROM order_items oi WHERE oi.order_id = o.id)
WHERE o.id = $1
`

func (q *Queries) RefreshOrderTotal(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, refreshOrderTotal, id)
	return err
}

const setOrderStatus = `-- name: SetOrderStatus :exec
UPDATE orders
SET status = $1::text,
    updated_at = now(),
    packed_at = CASE WHEN $1::text = 'packed' THEN now() ELSE packed_at END,
    shipped_at = CASE WHEN $1::text = 'shipped' THEN now() ELSE shipped_at END,
    canceled_at = CASE WHEN $1::text = 'canceled' THEN now() ELSE canceled_at END
WHERE id = $2
`

type SetOrderStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) error {
	_, err := q.db.Exec(ctx, setOrderStatus, arg.Status, arg.ID)
	return err
}
