// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: receipts.sql

package sqlc

import (
	"context"
	"time"
)

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO stock_receipts (reference, note, created_by)
VALUES ($1, $2, $3)
RETURNING id, created_at
`

type CreateReceiptParams struct {
	Reference *string `json:"reference"`
	Note      *string `json:"note"`
	CreatedBy *int64  `json:"created_by"`
}

type CreateReceiptRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (CreateReceiptRow, error) {
	row := q.db.QueryRow(ctx, createReceipt, arg.Reference, arg.Note, arg.CreatedBy)
	var i CreateReceiptRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
