// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock.sql

package sqlc

import (
	"context"
	"time"
)

const applyBalanceChange = `-- name: ApplyBalanceChange :one
UPDATE stock_balances
SET on_hand = on_hand + $1,
    reserved = reserved + $2,
    version = version + 1,
    updated_at = now()
WHERE product_id = $3
RETURNING on_hand, reserved
`

type ApplyBalanceChangeParams struct {
	QtyChange      int32 `json:"qty_change"`
	ReservedChange int32 `json:"reserved_change"`
	ProductID      int64 `json:"product_id"`
}

type ApplyBalanceChangeRow struct {
	OnHand   int32 `json:"on_hand"`
	Reserved int32 `json:"reserved"`
}

func (q *Queries) ApplyBalanceChange(ctx context.Context, arg ApplyBalanceChangeParams) (ApplyBalanceChangeRow, error) {
	row := q.db.QueryRow(ctx, applyBalanceChange, arg.QtyChange, arg.ReservedChange, arg.ProductID)
	var i ApplyBalanceChangeRow
	err := row.Scan(&i.OnHand, &i.Reserved)
	return i, err
}

const countMovements = `-- name: CountMovements :one
SELECT count(*)
FROM stock_movements m
WHERE ($1::bigint IS NULL OR m.product_id = $1::bigint)
  AND ($2::text IS NULL OR m.type = $2::text)
`

type CountMovementsParams struct {
	ProductID *int64  `json:"product_id"`
	Type      *string `json:"type"`
}

func (q *Queries) CountMovements(ctx context.Context, arg CountMovementsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMovements, arg.ProductID, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMovement = `-- name: GetMovement :one
SELECT m.id, m.product_id, m.type, m.qty_change, m.reserved_change, m.ref_type, m.reverses_id,
       m.created_at,
       EXISTS (SELECT 1 FROM stock_movements r WHERE r.reverses_id = m.id) AS reversed
FROM stock_movements m
WHERE m.id = $1
`

type GetMovementRow struct {
	ID             int64     `json:"id"`
	ProductID      int64     `json:"product_id"`
	Type           string    `json:"type"`
	QtyChange      int32     `json:"qty_change"`
	ReservedChange int32     `json:"reserved_change"`
	RefType        *string   `json:"ref_type"`
	ReversesID     *int64    `json:"reverses_id"`
	CreatedAt      time.Time `json:"created_at"`
	Reversed       bool      `json:"reversed"`
}

func (q *Queries) GetMovement(ctx context.Context, id int64) (GetMovementRow, error) {
	row := q.db.QueryRow(ctx, getMovement, id)
	var i GetMovementRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Type,
		&i.QtyChange,
		&i.ReservedChange,
		&i.RefType,
		&i.ReversesID,
		&i.CreatedAt,
		&i.Reversed,
	)
	return i, err
}

const insertMovement = `-- name: InsertMovement :one
INSERT INTO stock_movements (
    product_id, type, qty_change, reserved_change, ref_type, ref_id,
    reason, note, created_by, on_hand_after, reserved_after, reverses_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12
)
RETURNING id, created_at
`

type InsertMovementParams struct {
	ProductID      int64   `json:"product_id"`
	Type           string  `json:"type"`
	QtyChange      int32   `json:"qty_change"`
	ReservedChange int32   `json:"reserved_change"`
	RefType        *string `json:"ref_type"`
	RefID          *int64  `json:"ref_id"`
	Reason         *string `json:"reason"`
	Note           *string `json:"note"`
	CreatedBy      *int64  `json:"created_by"`
	OnHandAfter    int32   `json:"on_hand_after"`
	ReservedAfter  int32   `json:"reserved_after"`
	ReversesID     *int64  `json:"reverses_id"`
}

type InsertMovementRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertMovement(ctx context.Context, arg InsertMovementParams) (InsertMovementRow, error) {
	row := q.db.QueryRow(ctx, insertMovement,
		arg.ProductID,
		arg.Type,
		arg.QtyChange,
		arg.ReservedChange,
		arg.RefType,
		arg.RefID,
		arg.Reason,
		arg.Note,
		arg.CreatedBy,
		arg.OnHandAfter,
		arg.ReservedAfter,
		arg.ReversesID,
	)
	var i InsertMovementRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listMovements = `-- name: ListMovements :many
SELECT m.id, m.product_id, p.sku, p.name AS product_name, m.type, m.qty_change,
       m.reserved_change, m.on_hand_after, m.reserved_after, m.ref_type, m.ref_id,
       o.order_no, o.channel AS order_channel, m.reason, m.note, u.name AS created_by_name,
       m.created_at, m.reverses_id,
       EXISTS (SELECT 1 FROM stock_movements r WHERE r.reverses_id = m.id) AS reversed
FROM stock_movements m
JOIN products p ON p.id = m.product_id
LEFT JOIN orders o ON m.ref_type = 'order' AND o.id = m.ref_id
LEFT JOIN users u ON u.id = m.created_by
WHERE ($1::bigint IS NULL OR m.product_id = $1::bigint)
  AND ($2::text IS NULL OR m.type = $2::text)
ORDER BY m.created_at DESC, m.id DESC
LIMIT $4 OFFSET $3
`

type ListMovementsParams struct {
	ProductID  *int64  `json:"product_id"`
	Type       *string `json:"type"`
	PageOffset int32   `json:"page_offset"`
	PageLimit  int32   `json:"page_limit"`
}

type ListMovementsRow struct {
	ID             int64     `json:"id"`
	ProductID      int64     `json:"product_id"`
	Sku            string    `json:"sku"`
	ProductName    string    `json:"product_name"`
	Type           string    `json:"type"`
	QtyChange      int32     `json:"qty_change"`
	ReservedChange int32     `json:"reserved_change"`
	OnHandAfter    int32     `json:"on_hand_after"`
	ReservedAfter  int32     `json:"reserved_after"`
	RefType        *string   `json:"ref_type"`
	RefID          *int64    `json:"ref_id"`
	OrderNo        *string   `json:"order_no"`
	OrderChannel   *string   `json:"order_channel"`
	Reason         *string   `json:"reason"`
	Note           *string   `json:"note"`
	CreatedByName  *string   `json:"created_by_name"`
	CreatedAt      time.Time `json:"created_at"`
	ReversesID     *int64    `json:"reverses_id"`
	Reversed       bool      `json:"reversed"`
}

func (q *Queries) ListMovements(ctx context.Context, arg ListMovementsParams) ([]ListMovementsRow, error) {
	rows, err := q.db.Query(ctx, listMovements,
		arg.ProductID,
		arg.Type,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMovementsRow{}
	for rows.Next() {
		var i ListMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.ProductName,
			&i.Type,
			&i.QtyChange,
			&i.ReservedChange,
			&i.OnHandAfter,
			&i.ReservedAfter,
			&i.RefType,
			&i.RefID,
			&i.OrderNo,
			&i.OrderChannel,
			&i.Reason,
			&i.Note,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.ReversesID,
			&i.Reversed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStockRows = `-- name: LockStockRows :many
SELECT b.product_id, b.on_hand, b.reserved, p.sku, p.name, p.price, p.is_active
FROM stock_balances b
JOIN products p ON p.id = b.product_id
WHERE b.product_id = ANY($1::bigint[])
ORDER BY b.product_id
FOR UPDATE OF b
`

type LockStockRowsRow struct {
	ProductID int64  `json:"product_id"`
	OnHand    int32  `json:"on_hand"`
	Reserved  int32  `json:"reserved"`
	Sku       string `json:"sku"`
	Name      string `json:"name"`
	Price     string `json:"price"`
	IsActive  bool   `json:"is_active"`
}

func (q *Queries) LockStockRows(ctx context.Context, productIds []int64) ([]LockStockRowsRow, error) {
	rows, err := q.db.Query(ctx, lockStockRows, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockStockRowsRow{}
	for rows.Next() {
		var i LockStockRowsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.OnHand,
			&i.Reserved,
			&i.Sku,
			&i.Name,
			&i.Price,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
